// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRqgorj08WdLoxTSRdltJ3QdVJh4yvg0',
    appId: '1:620337587532:web:30e1eb250b30d4bd129be9',
    messagingSenderId: '620337587532',
    projectId: 'chat-clean',
    authDomain: 'chat-clean.firebaseapp.com',
    storageBucket: 'chat-clean.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9002LkQmyx4mdCB-sxGjZVkP-5HVjPFg',
    appId: '1:620337587532:android:cd19d9df945ffdab129be9',
    messagingSenderId: '620337587532',
    projectId: 'chat-clean',
    storageBucket: 'chat-clean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7tb1vvPmg1PRj80DrftzVoYVTyCuABQ',
    appId: '1:620337587532:ios:cf7f150a707fdbf6129be9',
    messagingSenderId: '620337587532',
    projectId: 'chat-clean',
    storageBucket: 'chat-clean.appspot.com',
    iosClientId: '620337587532-1lp779kjubnpo8n3rd8lpfh5k0do15g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7tb1vvPmg1PRj80DrftzVoYVTyCuABQ',
    appId: '1:620337587532:ios:cf7f150a707fdbf6129be9',
    messagingSenderId: '620337587532',
    projectId: 'chat-clean',
    storageBucket: 'chat-clean.appspot.com',
    iosClientId: '620337587532-1lp779kjubnpo8n3rd8lpfh5k0do15g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );
}
